### ISSUE TITLE
tiny typo in the train_demo.py

### ISSUE THREAD

**Issue by WJ714** [akashkoppa/StressNet#1]
Dear Akash,
Thanks for sharing this super interesting tutorial!

Just noticed a tiny typo in the train_demo.py file:
Original: `flxsit = pd.read_hdf(path_or_buf = flxnet["stn"],   key="site")`
Shoud (might) be: `flxsit = pd.read_hdf(path_or_buf = flxnet["stn"],   key="siteda")`
It is a super tiny typo while for new birds regarding the .h5 format could be a small obstacle

Thanks.
Weijie Zhang

**Comment by akashkoppa** [comment]
Hi Weijie, 

Thank you for identifying the typo. I have fixed. I had a couple of different version with key = "site". I will check the other codes as well. 

Best 
Akash
